// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: publishers.proto

package books

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishersRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email       string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber string `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Address     string `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *PublishersRes) Reset() {
	*x = PublishersRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_publishers_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishersRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishersRes) ProtoMessage() {}

func (x *PublishersRes) ProtoReflect() protoreflect.Message {
	mi := &file_publishers_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishersRes.ProtoReflect.Descriptor instead.
func (*PublishersRes) Descriptor() ([]byte, []int) {
	return file_publishers_proto_rawDescGZIP(), []int{0}
}

func (x *PublishersRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PublishersRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PublishersRes) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *PublishersRes) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *PublishersRes) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type PublishersCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email       string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber string `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Address     string `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *PublishersCreateReq) Reset() {
	*x = PublishersCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_publishers_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishersCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishersCreateReq) ProtoMessage() {}

func (x *PublishersCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_publishers_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishersCreateReq.ProtoReflect.Descriptor instead.
func (*PublishersCreateReq) Descriptor() ([]byte, []int) {
	return file_publishers_proto_rawDescGZIP(), []int{1}
}

func (x *PublishersCreateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PublishersCreateReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *PublishersCreateReq) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *PublishersCreateReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type PublishersGetByIdRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Publishers *PublishersRes `protobuf:"bytes,1,opt,name=publishers,proto3" json:"publishers,omitempty"`
}

func (x *PublishersGetByIdRes) Reset() {
	*x = PublishersGetByIdRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_publishers_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishersGetByIdRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishersGetByIdRes) ProtoMessage() {}

func (x *PublishersGetByIdRes) ProtoReflect() protoreflect.Message {
	mi := &file_publishers_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishersGetByIdRes.ProtoReflect.Descriptor instead.
func (*PublishersGetByIdRes) Descriptor() ([]byte, []int) {
	return file_publishers_proto_rawDescGZIP(), []int{2}
}

func (x *PublishersGetByIdRes) GetPublishers() *PublishersRes {
	if x != nil {
		return x.Publishers
	}
	return nil
}

type PublishersGetAllRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Publishers []*PublishersRes `protobuf:"bytes,1,rep,name=publishers,proto3" json:"publishers,omitempty"`
}

func (x *PublishersGetAllRes) Reset() {
	*x = PublishersGetAllRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_publishers_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishersGetAllRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishersGetAllRes) ProtoMessage() {}

func (x *PublishersGetAllRes) ProtoReflect() protoreflect.Message {
	mi := &file_publishers_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishersGetAllRes.ProtoReflect.Descriptor instead.
func (*PublishersGetAllRes) Descriptor() ([]byte, []int) {
	return file_publishers_proto_rawDescGZIP(), []int{3}
}

func (x *PublishersGetAllRes) GetPublishers() []*PublishersRes {
	if x != nil {
		return x.Publishers
	}
	return nil
}

type PublishersUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Publisher *PublishersRes `protobuf:"bytes,1,opt,name=publisher,proto3" json:"publisher,omitempty"`
}

func (x *PublishersUpdateReq) Reset() {
	*x = PublishersUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_publishers_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishersUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishersUpdateReq) ProtoMessage() {}

func (x *PublishersUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_publishers_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishersUpdateReq.ProtoReflect.Descriptor instead.
func (*PublishersUpdateReq) Descriptor() ([]byte, []int) {
	return file_publishers_proto_rawDescGZIP(), []int{4}
}

func (x *PublishersUpdateReq) GetPublisher() *PublishersRes {
	if x != nil {
		return x.Publisher
	}
	return nil
}

type PublishersGetAllReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address string  `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Page    *Filter `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *PublishersGetAllReq) Reset() {
	*x = PublishersGetAllReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_publishers_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishersGetAllReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishersGetAllReq) ProtoMessage() {}

func (x *PublishersGetAllReq) ProtoReflect() protoreflect.Message {
	mi := &file_publishers_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishersGetAllReq.ProtoReflect.Descriptor instead.
func (*PublishersGetAllReq) Descriptor() ([]byte, []int) {
	return file_publishers_proto_rawDescGZIP(), []int{5}
}

func (x *PublishersGetAllReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PublishersGetAllReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PublishersGetAllReq) GetPage() *Filter {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_publishers_proto protoreflect.FileDescriptor

var file_publishers_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x1a, 0x0d, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x86, 0x01, 0x0a, 0x0d, 0x50, 0x75, 0x62,
	0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e,
	0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x22, 0x7c, 0x0a, 0x13, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x73, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22,
	0x4c, 0x0a, 0x14, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x73, 0x47, 0x65, 0x74,
	0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x12, 0x34, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x62, 0x6f,
	0x6f, 0x6b, 0x73, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x73, 0x52, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x73, 0x22, 0x4b, 0x0a,
	0x13, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x73, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x52, 0x65, 0x73, 0x12, 0x34, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65,
	0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x73,
	0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x52, 0x0a,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x73, 0x22, 0x49, 0x0a, 0x13, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x32, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x50, 0x75, 0x62,
	0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x73, 0x68, 0x65, 0x72, 0x22, 0x66, 0x0a, 0x13, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68,
	0x65, 0x72, 0x73, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x21, 0x0a, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x73,
	0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x32, 0x8e, 0x02,
	0x0a, 0x11, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x73, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x2b, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x14, 0x2e,
	0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x73,
	0x52, 0x65, 0x73, 0x1a, 0x0b, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x56, 0x6f, 0x69, 0x64,
	0x12, 0x33, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x12, 0x0b, 0x2e, 0x62, 0x6f,
	0x6f, 0x6b, 0x73, 0x2e, 0x42, 0x79, 0x49, 0x64, 0x1a, 0x1b, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x73,
	0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x73, 0x47, 0x65, 0x74, 0x42, 0x79,
	0x49, 0x64, 0x52, 0x65, 0x73, 0x12, 0x40, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x12,
	0x1a, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65,
	0x72, 0x73, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x62, 0x6f,
	0x6f, 0x6b, 0x73, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x73, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x31, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x12, 0x1a, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73,
	0x68, 0x65, 0x72, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e,
	0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x06, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x12, 0x0b, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x42, 0x79, 0x49,
	0x64, 0x1a, 0x0b, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x42, 0x10,
	0x5a, 0x0e, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_publishers_proto_rawDescOnce sync.Once
	file_publishers_proto_rawDescData = file_publishers_proto_rawDesc
)

func file_publishers_proto_rawDescGZIP() []byte {
	file_publishers_proto_rawDescOnce.Do(func() {
		file_publishers_proto_rawDescData = protoimpl.X.CompressGZIP(file_publishers_proto_rawDescData)
	})
	return file_publishers_proto_rawDescData
}

var file_publishers_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_publishers_proto_goTypes = []interface{}{
	(*PublishersRes)(nil),        // 0: books.PublishersRes
	(*PublishersCreateReq)(nil),  // 1: books.PublishersCreateReq
	(*PublishersGetByIdRes)(nil), // 2: books.PublishersGetByIdRes
	(*PublishersGetAllRes)(nil),  // 3: books.PublishersGetAllRes
	(*PublishersUpdateReq)(nil),  // 4: books.PublishersUpdateReq
	(*PublishersGetAllReq)(nil),  // 5: books.PublishersGetAllReq
	(*Filter)(nil),               // 6: books.Filter
	(*ById)(nil),                 // 7: books.ById
	(*Void)(nil),                 // 8: books.Void
}
var file_publishers_proto_depIdxs = []int32{
	0, // 0: books.PublishersGetByIdRes.publishers:type_name -> books.PublishersRes
	0, // 1: books.PublishersGetAllRes.publishers:type_name -> books.PublishersRes
	0, // 2: books.PublishersUpdateReq.publisher:type_name -> books.PublishersRes
	6, // 3: books.PublishersGetAllReq.page:type_name -> books.Filter
	0, // 4: books.PublishersService.Create:input_type -> books.PublishersRes
	7, // 5: books.PublishersService.GetById:input_type -> books.ById
	5, // 6: books.PublishersService.GetAll:input_type -> books.PublishersGetAllReq
	4, // 7: books.PublishersService.Update:input_type -> books.PublishersUpdateReq
	7, // 8: books.PublishersService.Delete:input_type -> books.ById
	8, // 9: books.PublishersService.Create:output_type -> books.Void
	2, // 10: books.PublishersService.GetById:output_type -> books.PublishersGetByIdRes
	3, // 11: books.PublishersService.GetAll:output_type -> books.PublishersGetAllRes
	8, // 12: books.PublishersService.Update:output_type -> books.Void
	8, // 13: books.PublishersService.Delete:output_type -> books.Void
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_publishers_proto_init() }
func file_publishers_proto_init() {
	if File_publishers_proto != nil {
		return
	}
	file_common2_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_publishers_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishersRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_publishers_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishersCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_publishers_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishersGetByIdRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_publishers_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishersGetAllRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_publishers_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishersUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_publishers_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishersGetAllReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_publishers_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_publishers_proto_goTypes,
		DependencyIndexes: file_publishers_proto_depIdxs,
		MessageInfos:      file_publishers_proto_msgTypes,
	}.Build()
	File_publishers_proto = out.File
	file_publishers_proto_rawDesc = nil
	file_publishers_proto_goTypes = nil
	file_publishers_proto_depIdxs = nil
}
