// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: authors.proto

package books

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthorsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Biography string `protobuf:"bytes,3,opt,name=biography,proto3" json:"biography,omitempty"`
}

func (x *AuthorsRes) Reset() {
	*x = AuthorsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authors_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorsRes) ProtoMessage() {}

func (x *AuthorsRes) ProtoReflect() protoreflect.Message {
	mi := &file_authors_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorsRes.ProtoReflect.Descriptor instead.
func (*AuthorsRes) Descriptor() ([]byte, []int) {
	return file_authors_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorsRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuthorsRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AuthorsRes) GetBiography() string {
	if x != nil {
		return x.Biography
	}
	return ""
}

type AuthorsCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Biography string `protobuf:"bytes,2,opt,name=biography,proto3" json:"biography,omitempty"`
}

func (x *AuthorsCreateReq) Reset() {
	*x = AuthorsCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authors_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorsCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorsCreateReq) ProtoMessage() {}

func (x *AuthorsCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_authors_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorsCreateReq.ProtoReflect.Descriptor instead.
func (*AuthorsCreateReq) Descriptor() ([]byte, []int) {
	return file_authors_proto_rawDescGZIP(), []int{1}
}

func (x *AuthorsCreateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AuthorsCreateReq) GetBiography() string {
	if x != nil {
		return x.Biography
	}
	return ""
}

type AuthorsGetByIdRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Authors *AuthorsRes `protobuf:"bytes,1,opt,name=authors,proto3" json:"authors,omitempty"`
}

func (x *AuthorsGetByIdRes) Reset() {
	*x = AuthorsGetByIdRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authors_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorsGetByIdRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorsGetByIdRes) ProtoMessage() {}

func (x *AuthorsGetByIdRes) ProtoReflect() protoreflect.Message {
	mi := &file_authors_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorsGetByIdRes.ProtoReflect.Descriptor instead.
func (*AuthorsGetByIdRes) Descriptor() ([]byte, []int) {
	return file_authors_proto_rawDescGZIP(), []int{2}
}

func (x *AuthorsGetByIdRes) GetAuthors() *AuthorsRes {
	if x != nil {
		return x.Authors
	}
	return nil
}

type AuthorsGetAllRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Authors []*AuthorsRes `protobuf:"bytes,1,rep,name=authors,proto3" json:"authors,omitempty"`
}

func (x *AuthorsGetAllRes) Reset() {
	*x = AuthorsGetAllRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authors_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorsGetAllRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorsGetAllRes) ProtoMessage() {}

func (x *AuthorsGetAllRes) ProtoReflect() protoreflect.Message {
	mi := &file_authors_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorsGetAllRes.ProtoReflect.Descriptor instead.
func (*AuthorsGetAllRes) Descriptor() ([]byte, []int) {
	return file_authors_proto_rawDescGZIP(), []int{3}
}

func (x *AuthorsGetAllRes) GetAuthors() []*AuthorsRes {
	if x != nil {
		return x.Authors
	}
	return nil
}

type AuthorsUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Author *AuthorsRes `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
}

func (x *AuthorsUpdateReq) Reset() {
	*x = AuthorsUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authors_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorsUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorsUpdateReq) ProtoMessage() {}

func (x *AuthorsUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_authors_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorsUpdateReq.ProtoReflect.Descriptor instead.
func (*AuthorsUpdateReq) Descriptor() ([]byte, []int) {
	return file_authors_proto_rawDescGZIP(), []int{4}
}

func (x *AuthorsUpdateReq) GetAuthor() *AuthorsRes {
	if x != nil {
		return x.Author
	}
	return nil
}

type AuthorsGetAllReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Page *Filter `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *AuthorsGetAllReq) Reset() {
	*x = AuthorsGetAllReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authors_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorsGetAllReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorsGetAllReq) ProtoMessage() {}

func (x *AuthorsGetAllReq) ProtoReflect() protoreflect.Message {
	mi := &file_authors_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorsGetAllReq.ProtoReflect.Descriptor instead.
func (*AuthorsGetAllReq) Descriptor() ([]byte, []int) {
	return file_authors_proto_rawDescGZIP(), []int{5}
}

func (x *AuthorsGetAllReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AuthorsGetAllReq) GetPage() *Filter {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_authors_proto protoreflect.FileDescriptor

var file_authors_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x1a, 0x0d, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x32, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4e, 0x0a, 0x0a, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73,
	0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x69, 0x6f, 0x67, 0x72,
	0x61, 0x70, 0x68, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x69, 0x6f, 0x67,
	0x72, 0x61, 0x70, 0x68, 0x79, 0x22, 0x44, 0x0a, 0x10, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x62, 0x69, 0x6f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x62, 0x69, 0x6f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x79, 0x22, 0x40, 0x0a, 0x11, 0x41,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73,
	0x12, 0x2b, 0x0a, 0x07, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x73, 0x52, 0x65, 0x73, 0x52, 0x07, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x22, 0x3f, 0x0a,
	0x10, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65,
	0x73, 0x12, 0x2b, 0x0a, 0x07, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x73, 0x52, 0x65, 0x73, 0x52, 0x07, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x22, 0x3d,
	0x0a, 0x10, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x29, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x73, 0x52, 0x65, 0x73, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x22, 0x49, 0x0a,
	0x10, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65,
	0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x32, 0xfc, 0x01, 0x0a, 0x0e, 0x41, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x11, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x41, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x73, 0x1a, 0x0b, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x73,
	0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x30, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64,
	0x12, 0x0b, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x42, 0x79, 0x49, 0x64, 0x1a, 0x18, 0x2e,
	0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x47, 0x65, 0x74,
	0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x12, 0x3a, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x12, 0x17, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x73, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x62, 0x6f, 0x6f,
	0x6b, 0x73, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x52, 0x65, 0x73, 0x12, 0x2e, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x17, 0x2e,
	0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x56,
	0x6f, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x0b, 0x2e,
	0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x42, 0x79, 0x49, 0x64, 0x1a, 0x0b, 0x2e, 0x62, 0x6f, 0x6f,
	0x6b, 0x73, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x42, 0x10, 0x5a, 0x0e, 0x67, 0x65, 0x6e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_authors_proto_rawDescOnce sync.Once
	file_authors_proto_rawDescData = file_authors_proto_rawDesc
)

func file_authors_proto_rawDescGZIP() []byte {
	file_authors_proto_rawDescOnce.Do(func() {
		file_authors_proto_rawDescData = protoimpl.X.CompressGZIP(file_authors_proto_rawDescData)
	})
	return file_authors_proto_rawDescData
}

var file_authors_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_authors_proto_goTypes = []interface{}{
	(*AuthorsRes)(nil),        // 0: books.AuthorsRes
	(*AuthorsCreateReq)(nil),  // 1: books.AuthorsCreateReq
	(*AuthorsGetByIdRes)(nil), // 2: books.AuthorsGetByIdRes
	(*AuthorsGetAllRes)(nil),  // 3: books.AuthorsGetAllRes
	(*AuthorsUpdateReq)(nil),  // 4: books.AuthorsUpdateReq
	(*AuthorsGetAllReq)(nil),  // 5: books.AuthorsGetAllReq
	(*Filter)(nil),            // 6: books.Filter
	(*ById)(nil),              // 7: books.ById
	(*Void)(nil),              // 8: books.Void
}
var file_authors_proto_depIdxs = []int32{
	0, // 0: books.AuthorsGetByIdRes.authors:type_name -> books.AuthorsRes
	0, // 1: books.AuthorsGetAllRes.authors:type_name -> books.AuthorsRes
	0, // 2: books.AuthorsUpdateReq.author:type_name -> books.AuthorsRes
	6, // 3: books.AuthorsGetAllReq.page:type_name -> books.Filter
	0, // 4: books.AuthorsService.Create:input_type -> books.AuthorsRes
	7, // 5: books.AuthorsService.GetById:input_type -> books.ById
	5, // 6: books.AuthorsService.GetAll:input_type -> books.AuthorsGetAllReq
	4, // 7: books.AuthorsService.Update:input_type -> books.AuthorsUpdateReq
	7, // 8: books.AuthorsService.Delete:input_type -> books.ById
	8, // 9: books.AuthorsService.Create:output_type -> books.Void
	2, // 10: books.AuthorsService.GetById:output_type -> books.AuthorsGetByIdRes
	3, // 11: books.AuthorsService.GetAll:output_type -> books.AuthorsGetAllRes
	8, // 12: books.AuthorsService.Update:output_type -> books.Void
	8, // 13: books.AuthorsService.Delete:output_type -> books.Void
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_authors_proto_init() }
func file_authors_proto_init() {
	if File_authors_proto != nil {
		return
	}
	file_common2_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_authors_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authors_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorsCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authors_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorsGetByIdRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authors_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorsGetAllRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authors_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorsUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authors_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorsGetAllReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_authors_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authors_proto_goTypes,
		DependencyIndexes: file_authors_proto_depIdxs,
		MessageInfos:      file_authors_proto_msgTypes,
	}.Build()
	File_authors_proto = out.File
	file_authors_proto_rawDesc = nil
	file_authors_proto_goTypes = nil
	file_authors_proto_depIdxs = nil
}
