// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: languages.proto

package books

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LanguagesRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *LanguagesRes) Reset() {
	*x = LanguagesRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_languages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LanguagesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LanguagesRes) ProtoMessage() {}

func (x *LanguagesRes) ProtoReflect() protoreflect.Message {
	mi := &file_languages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LanguagesRes.ProtoReflect.Descriptor instead.
func (*LanguagesRes) Descriptor() ([]byte, []int) {
	return file_languages_proto_rawDescGZIP(), []int{0}
}

func (x *LanguagesRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LanguagesRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LanguagesCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *LanguagesCreateReq) Reset() {
	*x = LanguagesCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_languages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LanguagesCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LanguagesCreateReq) ProtoMessage() {}

func (x *LanguagesCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_languages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LanguagesCreateReq.ProtoReflect.Descriptor instead.
func (*LanguagesCreateReq) Descriptor() ([]byte, []int) {
	return file_languages_proto_rawDescGZIP(), []int{1}
}

func (x *LanguagesCreateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LanguagesGetAllRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Languages []*LanguagesRes `protobuf:"bytes,1,rep,name=languages,proto3" json:"languages,omitempty"`
}

func (x *LanguagesGetAllRes) Reset() {
	*x = LanguagesGetAllRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_languages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LanguagesGetAllRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LanguagesGetAllRes) ProtoMessage() {}

func (x *LanguagesGetAllRes) ProtoReflect() protoreflect.Message {
	mi := &file_languages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LanguagesGetAllRes.ProtoReflect.Descriptor instead.
func (*LanguagesGetAllRes) Descriptor() ([]byte, []int) {
	return file_languages_proto_rawDescGZIP(), []int{2}
}

func (x *LanguagesGetAllRes) GetLanguages() []*LanguagesRes {
	if x != nil {
		return x.Languages
	}
	return nil
}

type LanguagesUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Language *LanguagesRes `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
}

func (x *LanguagesUpdateReq) Reset() {
	*x = LanguagesUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_languages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LanguagesUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LanguagesUpdateReq) ProtoMessage() {}

func (x *LanguagesUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_languages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LanguagesUpdateReq.ProtoReflect.Descriptor instead.
func (*LanguagesUpdateReq) Descriptor() ([]byte, []int) {
	return file_languages_proto_rawDescGZIP(), []int{3}
}

func (x *LanguagesUpdateReq) GetLanguage() *LanguagesRes {
	if x != nil {
		return x.Language
	}
	return nil
}

type LanguagesGetAllReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Page *Filter `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *LanguagesGetAllReq) Reset() {
	*x = LanguagesGetAllReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_languages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LanguagesGetAllReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LanguagesGetAllReq) ProtoMessage() {}

func (x *LanguagesGetAllReq) ProtoReflect() protoreflect.Message {
	mi := &file_languages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LanguagesGetAllReq.ProtoReflect.Descriptor instead.
func (*LanguagesGetAllReq) Descriptor() ([]byte, []int) {
	return file_languages_proto_rawDescGZIP(), []int{4}
}

func (x *LanguagesGetAllReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LanguagesGetAllReq) GetPage() *Filter {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_languages_proto protoreflect.FileDescriptor

var file_languages_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x1a, 0x0d, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x32, 0x0a, 0x0c, 0x4c, 0x61, 0x6e, 0x67, 0x75,
	0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x28, 0x0a, 0x12, 0x4c,
	0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x47, 0x0a, 0x12, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67,
	0x65, 0x73, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x31, 0x0a, 0x09, 0x6c,
	0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x52, 0x09, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x73, 0x22, 0x45,
	0x0a, 0x12, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x2f, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x4c,
	0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x73, 0x52, 0x08, 0x6c, 0x61, 0x6e,
	0x67, 0x75, 0x61, 0x67, 0x65, 0x22, 0x4b, 0x0a, 0x12, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67,
	0x65, 0x73, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x21, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x32, 0x81, 0x02, 0x0a, 0x10, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x73,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x12, 0x13, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61,
	0x67, 0x65, 0x73, 0x52, 0x65, 0x73, 0x1a, 0x0b, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x56,
	0x6f, 0x69, 0x64, 0x12, 0x2b, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x12, 0x0b,
	0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x42, 0x79, 0x49, 0x64, 0x1a, 0x13, 0x2e, 0x62, 0x6f,
	0x6f, 0x6b, 0x73, 0x2e, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x12, 0x3e, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x19, 0x2e, 0x62, 0x6f, 0x6f,
	0x6b, 0x73, 0x2e, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x73, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x4c, 0x61,
	0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x73, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73,
	0x12, 0x30, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x19, 0x2e, 0x62, 0x6f, 0x6f,
	0x6b, 0x73, 0x2e, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x73, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x56, 0x6f,
	0x69, 0x64, 0x12, 0x22, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x0b, 0x2e, 0x62,
	0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x42, 0x79, 0x49, 0x64, 0x1a, 0x0b, 0x2e, 0x62, 0x6f, 0x6f, 0x6b,
	0x73, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x42, 0x10, 0x5a, 0x0e, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_languages_proto_rawDescOnce sync.Once
	file_languages_proto_rawDescData = file_languages_proto_rawDesc
)

func file_languages_proto_rawDescGZIP() []byte {
	file_languages_proto_rawDescOnce.Do(func() {
		file_languages_proto_rawDescData = protoimpl.X.CompressGZIP(file_languages_proto_rawDescData)
	})
	return file_languages_proto_rawDescData
}

var file_languages_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_languages_proto_goTypes = []interface{}{
	(*LanguagesRes)(nil),       // 0: books.LanguagesRes
	(*LanguagesCreateReq)(nil), // 1: books.LanguagesCreateReq
	(*LanguagesGetAllRes)(nil), // 2: books.LanguagesGetAllRes
	(*LanguagesUpdateReq)(nil), // 3: books.LanguagesUpdateReq
	(*LanguagesGetAllReq)(nil), // 4: books.LanguagesGetAllReq
	(*Filter)(nil),             // 5: books.Filter
	(*ById)(nil),               // 6: books.ById
	(*Void)(nil),               // 7: books.Void
}
var file_languages_proto_depIdxs = []int32{
	0, // 0: books.LanguagesGetAllRes.languages:type_name -> books.LanguagesRes
	0, // 1: books.LanguagesUpdateReq.language:type_name -> books.LanguagesRes
	5, // 2: books.LanguagesGetAllReq.page:type_name -> books.Filter
	0, // 3: books.LanguagesService.Create:input_type -> books.LanguagesRes
	6, // 4: books.LanguagesService.GetById:input_type -> books.ById
	4, // 5: books.LanguagesService.GetAll:input_type -> books.LanguagesGetAllReq
	3, // 6: books.LanguagesService.Update:input_type -> books.LanguagesUpdateReq
	6, // 7: books.LanguagesService.Delete:input_type -> books.ById
	7, // 8: books.LanguagesService.Create:output_type -> books.Void
	0, // 9: books.LanguagesService.GetById:output_type -> books.LanguagesRes
	2, // 10: books.LanguagesService.GetAll:output_type -> books.LanguagesGetAllRes
	7, // 11: books.LanguagesService.Update:output_type -> books.Void
	7, // 12: books.LanguagesService.Delete:output_type -> books.Void
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_languages_proto_init() }
func file_languages_proto_init() {
	if File_languages_proto != nil {
		return
	}
	file_common2_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_languages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LanguagesRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_languages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LanguagesCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_languages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LanguagesGetAllRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_languages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LanguagesUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_languages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LanguagesGetAllReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_languages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_languages_proto_goTypes,
		DependencyIndexes: file_languages_proto_depIdxs,
		MessageInfos:      file_languages_proto_msgTypes,
	}.Build()
	File_languages_proto = out.File
	file_languages_proto_rawDesc = nil
	file_languages_proto_goTypes = nil
	file_languages_proto_depIdxs = nil
}
