// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: translators.proto

package books

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TranslatorsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Surname string `protobuf:"bytes,3,opt,name=surname,proto3" json:"surname,omitempty"`
}

func (x *TranslatorsRes) Reset() {
	*x = TranslatorsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_translators_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TranslatorsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslatorsRes) ProtoMessage() {}

func (x *TranslatorsRes) ProtoReflect() protoreflect.Message {
	mi := &file_translators_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslatorsRes.ProtoReflect.Descriptor instead.
func (*TranslatorsRes) Descriptor() ([]byte, []int) {
	return file_translators_proto_rawDescGZIP(), []int{0}
}

func (x *TranslatorsRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TranslatorsRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TranslatorsRes) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

type TranslatorsCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Surname string `protobuf:"bytes,2,opt,name=surname,proto3" json:"surname,omitempty"`
}

func (x *TranslatorsCreateReq) Reset() {
	*x = TranslatorsCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_translators_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TranslatorsCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslatorsCreateReq) ProtoMessage() {}

func (x *TranslatorsCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_translators_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslatorsCreateReq.ProtoReflect.Descriptor instead.
func (*TranslatorsCreateReq) Descriptor() ([]byte, []int) {
	return file_translators_proto_rawDescGZIP(), []int{1}
}

func (x *TranslatorsCreateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TranslatorsCreateReq) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

type TranslatorsGetAllRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Translators []*TranslatorsRes `protobuf:"bytes,1,rep,name=translators,proto3" json:"translators,omitempty"`
}

func (x *TranslatorsGetAllRes) Reset() {
	*x = TranslatorsGetAllRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_translators_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TranslatorsGetAllRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslatorsGetAllRes) ProtoMessage() {}

func (x *TranslatorsGetAllRes) ProtoReflect() protoreflect.Message {
	mi := &file_translators_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslatorsGetAllRes.ProtoReflect.Descriptor instead.
func (*TranslatorsGetAllRes) Descriptor() ([]byte, []int) {
	return file_translators_proto_rawDescGZIP(), []int{2}
}

func (x *TranslatorsGetAllRes) GetTranslators() []*TranslatorsRes {
	if x != nil {
		return x.Translators
	}
	return nil
}

type TranslatorsUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Translator *TranslatorsRes `protobuf:"bytes,1,opt,name=translator,proto3" json:"translator,omitempty"`
}

func (x *TranslatorsUpdateReq) Reset() {
	*x = TranslatorsUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_translators_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TranslatorsUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslatorsUpdateReq) ProtoMessage() {}

func (x *TranslatorsUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_translators_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslatorsUpdateReq.ProtoReflect.Descriptor instead.
func (*TranslatorsUpdateReq) Descriptor() ([]byte, []int) {
	return file_translators_proto_rawDescGZIP(), []int{3}
}

func (x *TranslatorsUpdateReq) GetTranslator() *TranslatorsRes {
	if x != nil {
		return x.Translator
	}
	return nil
}

type TranslatorsGetAllReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Surname string  `protobuf:"bytes,2,opt,name=surname,proto3" json:"surname,omitempty"`
	Page    *Filter `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *TranslatorsGetAllReq) Reset() {
	*x = TranslatorsGetAllReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_translators_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TranslatorsGetAllReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslatorsGetAllReq) ProtoMessage() {}

func (x *TranslatorsGetAllReq) ProtoReflect() protoreflect.Message {
	mi := &file_translators_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslatorsGetAllReq.ProtoReflect.Descriptor instead.
func (*TranslatorsGetAllReq) Descriptor() ([]byte, []int) {
	return file_translators_proto_rawDescGZIP(), []int{4}
}

func (x *TranslatorsGetAllReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TranslatorsGetAllReq) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *TranslatorsGetAllReq) GetPage() *Filter {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_translators_proto protoreflect.FileDescriptor

var file_translators_proto_rawDesc = []byte{
	0x0a, 0x11, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x1a, 0x0d, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4e, 0x0a, 0x0e, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x73, 0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x44, 0x0a, 0x14, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x4f, 0x0a, 0x14, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x37, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x6c, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x62,
	0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x73,
	0x52, 0x65, 0x73, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x73,
	0x22, 0x4d, 0x0a, 0x14, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x35, 0x0a, 0x0a, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x62,
	0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x73,
	0x52, 0x65, 0x73, 0x52, 0x0a, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x22,
	0x67, 0x0a, 0x14, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x32, 0x8d, 0x02, 0x0a, 0x12, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x2c, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x15, 0x2e, 0x62, 0x6f, 0x6f, 0x6b,
	0x73, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x73,
	0x1a, 0x0b, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x2d, 0x0a,
	0x07, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x12, 0x0b, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x73,
	0x2e, 0x42, 0x79, 0x49, 0x64, 0x1a, 0x15, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x73, 0x12, 0x42, 0x0a, 0x06,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x1b, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73,
	0x12, 0x32, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x2e, 0x62, 0x6f, 0x6f,
	0x6b, 0x73, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x2e,
	0x56, 0x6f, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x0b,
	0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x42, 0x79, 0x49, 0x64, 0x1a, 0x0b, 0x2e, 0x62, 0x6f,
	0x6f, 0x6b, 0x73, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x42, 0x10, 0x5a, 0x0e, 0x67, 0x65, 0x6e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_translators_proto_rawDescOnce sync.Once
	file_translators_proto_rawDescData = file_translators_proto_rawDesc
)

func file_translators_proto_rawDescGZIP() []byte {
	file_translators_proto_rawDescOnce.Do(func() {
		file_translators_proto_rawDescData = protoimpl.X.CompressGZIP(file_translators_proto_rawDescData)
	})
	return file_translators_proto_rawDescData
}

var file_translators_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_translators_proto_goTypes = []interface{}{
	(*TranslatorsRes)(nil),       // 0: books.TranslatorsRes
	(*TranslatorsCreateReq)(nil), // 1: books.TranslatorsCreateReq
	(*TranslatorsGetAllRes)(nil), // 2: books.TranslatorsGetAllRes
	(*TranslatorsUpdateReq)(nil), // 3: books.TranslatorsUpdateReq
	(*TranslatorsGetAllReq)(nil), // 4: books.TranslatorsGetAllReq
	(*Filter)(nil),               // 5: books.Filter
	(*ById)(nil),                 // 6: books.ById
	(*Void)(nil),                 // 7: books.Void
}
var file_translators_proto_depIdxs = []int32{
	0, // 0: books.TranslatorsGetAllRes.translators:type_name -> books.TranslatorsRes
	0, // 1: books.TranslatorsUpdateReq.translator:type_name -> books.TranslatorsRes
	5, // 2: books.TranslatorsGetAllReq.page:type_name -> books.Filter
	0, // 3: books.TranslatorsService.Create:input_type -> books.TranslatorsRes
	6, // 4: books.TranslatorsService.GetById:input_type -> books.ById
	4, // 5: books.TranslatorsService.GetAll:input_type -> books.TranslatorsGetAllReq
	3, // 6: books.TranslatorsService.Update:input_type -> books.TranslatorsUpdateReq
	6, // 7: books.TranslatorsService.Delete:input_type -> books.ById
	7, // 8: books.TranslatorsService.Create:output_type -> books.Void
	0, // 9: books.TranslatorsService.GetById:output_type -> books.TranslatorsRes
	2, // 10: books.TranslatorsService.GetAll:output_type -> books.TranslatorsGetAllRes
	7, // 11: books.TranslatorsService.Update:output_type -> books.Void
	7, // 12: books.TranslatorsService.Delete:output_type -> books.Void
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_translators_proto_init() }
func file_translators_proto_init() {
	if File_translators_proto != nil {
		return
	}
	file_common2_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_translators_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TranslatorsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_translators_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TranslatorsCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_translators_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TranslatorsGetAllRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_translators_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TranslatorsUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_translators_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TranslatorsGetAllReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_translators_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_translators_proto_goTypes,
		DependencyIndexes: file_translators_proto_depIdxs,
		MessageInfos:      file_translators_proto_msgTypes,
	}.Build()
	File_translators_proto = out.File
	file_translators_proto_rawDesc = nil
	file_translators_proto_goTypes = nil
	file_translators_proto_depIdxs = nil
}
